GET {{baseUrl}}/device HTTP/1.1
Content-Type: application/application/json
token: {{token}}

###

GET {{baseUrl}}/device/1 HTTP/1.1
Content-Type: application/application/json
token: {{token}}

###

POST {{baseUrl}}/device HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "DeviceName":"kol",
    "DeviceStatus":1,
}

###

PUT {{baseUrl}}/device HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "Id":8,
    "DeviceName":"kapinin"
}