version: "3"
services:
  serve:
    container_name: communication-of-things
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    expose:
      - 5000
    restart: 
    ports:
      - 
    environment:
      PORT: 5000
      API_KEY:
      DB_HOST:
      DB_USER:
      DB_PASS:
      DB_DATABASE:
    links:
      -
  database:
    container_name: 
    image: 
    ports:
      
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
